use simpler 'release' instead of 'non-prerelease' word in user-facing…
RobotsAndPencils/xcodes pull request #239
Opened 2022-11-09 13:37 UTC by pastey

… output

Hi,

Not sure if you'll find this PR useful and corresponding to your philosophy, but anyway...

I find current phrasing `Latest non-prerelease version available is...` a bit too complex. I would suggest to simplify it by replacing `non-prerelease` to plain... `release`.

I see that the same `NonPrerelease` term is used in variable names. If you find this suggestion feasible, then I can rename variables too.

Maybe you'll tell me that there's some deep idea behind `non-prerelease`, then I'm fine with that too :)

Thanks for the great tool that saves ton of my time!

2022-11-11 15:52 UTC, MattKiazyk requested changes
I aggee @pastey - can we change the enum as well so devs working on the project are less confused too!

2022-11-11 15:52 UTC, MattKiazyk commented on Sources/XcodesKit/XcodeInstaller.swift
>              case .noNonPrereleaseVersionAvailable:
Can't agree with you more! Can we go the next step and rename this enum as well?

2022-11-15 09:18 UTC, pastey commented on README.md
> +Even though xcodes is a command-line app, all of the normal functionality works in Xcode, like building, running, and running tests. You can even type text into Xcode's console when it prompts you fo
Fixed a small typo here. Not related to the PR, but would be nice to fix 🙏

2022-11-15 09:19 UTC, pastey commented
@MattKiazyk, please check 🙏

2022-11-18 01:52 UTC, MattKiazyk commented
Sorry @pastey can you rebase with the recent changes with runtime installs. Looks good otherwise.

2022-11-18 08:54 UTC, pastey commented
> Sorry @pastey can you rebase with the recent changes with runtime installs. Looks good otherwise.

Done. Hope I did it correctly (I'm more used to plain old merge)

2022-11-24 08:11 UTC, pastey commented
Hey, @MattKiazyk will you have a chance to take one more look at this PR?

2022-12-09 15:31 UTC, pastey commented
Hey, @MattKiazyk will you have a chance to take one more look at this PR?

2022-12-09 16:24 UTC, MattKiazyk approved these changes

2022-12-09 16:24 UTC, merged